const products = [
  {
    title: "Asian Sesame Edamame",
    image: "/product/asian_sesame_edamame.png",
    category: "Makanan & Minuman",
    company: "Green Snack",
    stok: 25,
    discount: 15,
    price_before_discount: 30000,
    price_after_discount: 25500,
  },
  {
    title: "Cafe Altura Coffee",
    image: "/product/cafe_altura.png",
    category: "Makanan & Minuman",
    company: "Cafe Altura",
    stok: 12,
    discount: 10,
    price_before_discount: 45000,
    price_after_discount: 40500,
  },
  {
    title: "Herbal Dandelion Drink",
    image: "/product/instant_herbal_beverage_with_dandelion.png",
    category: "Makanan & Minuman",
    company: "Herbal Drink",
    stok: 40,
    discount: 12,
    price_before_discount: 38000,
    price_after_discount: 33400,
  },
  {
    title: "Mighty Muffin",
    image: "/product/mighty_muffin.png",
    category: "Makanan & Minuman",
    company: "Mighty Foods",
    stok: 8,
    discount: 5,
    price_before_discount: 25000,
    price_after_discount: 23750,
  },
  {
    title: "Organic Latte Turmeric Glow",
    image: "/product/organic_latte_turmeric_glow.png",
    category: "Home Care",
    company: "Organic Farm",
    stok: 18,
    discount: 8,
    price_before_discount: 42000,
    price_after_discount: 38640,
  },
  {
    title: "Unsweetened Coconut Flakes",
    image: "/product/unsweetened_coconut_flakes.png",
    category: "Home Care",
    company: "Coco Farm",
    stok: 22,
    discount: 9,
    price_before_discount: 28000,
    price_after_discount: 25480,
  },
  {
    title: "Veggie Pops Broccoli Chedda",
    image: "/product/veggie_pops_broccoli_chedda.png",
    category: "Home Care",
    company: "Veggie Snacks",
    stok: 14,
    discount: 10,
    price_before_discount: 35000,
    price_after_discount: 31500,
  },
  {
    title: "Pistachio Body Butter",
    image: "/product/pistachio_butter.png",
    category: "Body Care",
    company: "Pista House",
    stok: 15,
    discount: 20,
    price_before_discount: 70000,
    price_after_discount: 56000,
  },
  {
    title: "Edamame Scrub",
    image: "/product/asian_sesame_edamame.png",
    category: "Body Care",
    company: "Glow Care",
    stok: 20,
    discount: 6,
    price_before_discount: 30000,
    price_after_discount: 28200,
  },
  {
    title: "Raspberry Body Lotion",
    image: "/product/raspberry_crumble_cashew_mix.png",
    category: "Body Care",
    company: "Nutty Glow",
    stok: 10,
    discount: 7,
    price_before_discount: 39000,
    price_after_discount: 36270,
  },
  {
    title: "Yuja Niacin Serum",
    image: "/product/yuja_niacin.png",
    category: "Skin Care",
    company: "Some By Mi",
    stok: 30,
    discount: 12,
    price_before_discount: 150000,
    price_after_discount: 132000,
  },
  {
    title: "Coconut Glow Cream",
    image: "/product/unsweetened_coconut_flakes.png",
    category: "Skin Care",
    company: "Coco Care",
    stok: 18,
    discount: 9,
    price_before_discount: 35000,
    price_after_discount: 31850,
  },
  {
    title: "Herbal Skin Toner",
    image: "/product/instant_herbal_beverage_with_dandelion.png",
    category: "Skin Care",
    company: "Herbal Beauty",
    stok: 25,
    discount: 10,
    price_before_discount: 40000,
    price_after_discount: 36000,
  },
  {
    title: "Pepsi Mainan Mini",
    image: "/product/pepsi.png",
    category: "Mainan",
    company: "Mini Toys",
    stok: 50,
    discount: 4,
    price_before_discount: 5000,
    price_after_discount: 5000,
  },
  {
    title: "Veggie Toy Pack",
    image: "/product/veggie_pops_broccoli_chedda.png",
    category: "Mainan",
    company: "ToyFarm",
    stok: 12,
    discount: 10,
    price_before_discount: 25000,
    price_after_discount: 22500,
  },
  {
    title: "Coconut Flakes Toy Set",
    image: "/product/unsweetened_coconut_flakes.png",
    category: "Mainan",
    company: "SnackToy",
    stok: 30,
    discount: 8,
    price_before_discount: 20000,
    price_after_discount: 18400,
  },
]

export default products;